spring: 
  profiles: 
    active: 
    - dev
---
server:
  port: 8001
spring:
  profiles :dev
  application:
    name: microservicecloud-config-provide-8001
  datasource:
    url: jdbc:mysql://localhost:3306/microservice1?serverTimezone=UTC&useUnicode=true&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
## 注册服务
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
  instance:
    instance-id: microservicecloud-config-provide-8001
    prefer-ip-address: true     #访问路径可以显示IP地址
    hostname: ${spring.cloud.client.ipAddress}
info:
  app.name: nwnusun-microservicecloud
  company.name: www.nwnusun.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
  
---
server:
  port: 8002
spring:
  profiles :test
  application:
    name: microservicecloud-config-provide-8002
  datasource:
    url: jdbc:mysql://localhost:3306/microservice1?serverTimezone=UTC&useUnicode=true&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
## 注册服务
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
  instance:
    instance-id: microservicecloud-config-provide-8002
    prefer-ip-address: true     #访问路径可以显示IP地址
    hostname: ${spring.cloud.client.ipAddress}
info:
  app.name: nwnusun-microservicecloud
  company.name: www.nwnusun.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$